import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createDefaultSite} from '../src/lib/designer/defaults.ts';
import {verifyPublishedResources} from '../src/lib/designer/resources.ts';
import {publicFontKey} from '../src/lib/designer/fonts.ts';
import {validateProcessingResult} from '../src/lib/processing-result.ts';
import {initializeCatalog,readCatalogSession,stageCatalogPart,commitCatalog,catalogRecycle,publishCatalog,catalogHistory,restoreCatalog,pagedRequestLimit,pageIndex,backupCatalog,catalogResources,snapshotCatalogSession,readCatalogRoot,readCatalogVersion,verifyPublicationBatch,requirePublicationVerification,previewCatalog} from '../src/lib/designer/catalog.ts';
function fixture(){const docs=new Map(),objects=new Map(),reads=[],writes=[];let revision=0,fail=false;const calls={get:0,fetch:0,mutate:0},r2={count:0};return {docs,objects,reads,writes,calls,r2,setFail:()=>fail=true,client:{getDocument:async id=>{calls.get++;reads.push(id);return structuredClone(docs.get(id));},fetch:async(q,p)=>{calls.fetch++;if(p.ids)reads.push(...p.ids);return p.ids?p.ids.flatMap(id=>docs.has(id)?[structuredClone(docs.get(id))]:[]):[...docs.values()].filter(d=>d._type==='designerRecycle'&&d.owner===p.owner&&d.active&&d._id>p.cursor).sort((a,b)=>a._id.localeCompare(b._id)).slice(0,51);},mutate:async ops=>{calls.mutate++;writes.push(Buffer.byteLength(JSON.stringify({mutations:ops})));if(fail){fail=false;throw Object.assign(new Error('fail'),{statusCode:409});}for(const m of ops){if(m.patch&&docs.get(m.patch.id)?._rev!==m.patch.ifRevisionID||m.create&&docs.has(m.create._id))throw Object.assign(new Error('conflict'),{statusCode:409});}for(const m of ops){const d=m.create??m.createIfNotExists;if(d){if(!docs.has(d._id))docs.set(d._id,{...structuredClone(d),_rev:`r${++revision}`});}else docs.set(m.patch.id,{...docs.get(m.patch.id),...structuredClone(m.patch.set),_rev:`r${++revision}`});}}},bucket:{put:async(key,text,o)=>{r2.count++;if(!objects.has(key))objects.set(key,{text,customMetadata:o.customMetadata,version:crypto.randomUUID(),uploaded:new Date()});},get:async key=>{r2.count++;const o=objects.get(key);return o?{...o,size:Buffer.byteLength(o.text),text:async()=>o.text}:null;},head:async key=>{r2.count++;return objects.get(key);},list:async({prefix,limit})=>{r2.count++;return {objects:[...objects].filter(([key])=>key.startsWith(prefix)).slice(0,limit).map(([key,o])=>({key,uploaded:o.uploaded})),truncated:false};}}};}
const fallback=async()=>createDefaultSite();const verify=async()=>{};
test('catalog accepts only the approved home hero bleed',()=>{
 const home=createDefaultSite().pages[0],image=home.blocks[0].elements[0];
 image.styles.desktop={x:0,y:-99.94,width:100,height:160.24};
 assert.equal(pageIndex(home).issues.length,0);
 image.id='another-image';
 assert.ok(pageIndex(home).issues.some(issue=>issue.widths.includes(1440)));
});
test('linked unpublished pages and deleted anchors block publication without changing public content',async()=>{
 const f=fixture();await initializeCatalog(f.client,f.bucket,'owner',fallback);let s=await readCatalogSession(f.client);
 const target=page(9);target.blocks=[{id:'target-anchor',name:'Target section',type:'flow',styles:{desktop:{}},elements:[]}];
 const header=structuredClone(s.header);header.blocks[0].elements.push({id:'dependency-link',name:'Dependency',type:'text',text:'Dependency',link:{pageId:target.id,anchor:'target-anchor',newTab:true},styles:{desktop:{}}});
 const a=await stageCatalogPart(f.client,'owner',s.revision,target.id,target,verify),b=await stageCatalogPart(f.client,'owner',s.revision,'header',header,verify);
 s=await commitCatalog(f.client,'owner',{revision:s.revision,receipts:[a.receipt,b.receipt]});
 await assert.rejects(()=>publishCatalog(f.client,f.bucket,'owner',{revision:s.revision,publishedRevision:null,scope:['header'],confirmed:true},fallback,verify),e=>e.status===409&&e.message.includes(target.id));
 assert.equal(f.docs.has('designer-site'),false);
 s=await publishCatalog(f.client,f.bucket,'owner',{revision:s.revision,publishedRevision:null,scope:['header',target.id],confirmed:true},fallback,verify);
 const publicBefore=structuredClone(f.docs.get('designer-site'));
 target.blocks[0].deleted=true;const removed=await stageCatalogPart(f.client,'owner',s.revision,target.id,target,verify);
 s=await commitCatalog(f.client,'owner',{revision:s.revision,receipts:[removed.receipt]});
 await assert.rejects(()=>publishCatalog(f.client,f.bucket,'owner',{revision:s.revision,publishedRevision:s.publishedRevision,scope:[target.id],confirmed:true},fallback,verify),e=>e.status===409&&e.message.includes('target-anchor'));
 assert.deepEqual(f.docs.get('designer-site'),publicBefore);
});
const resetCalls=f=>{Object.assign(f.calls,{get:0,fetch:0,mutate:0});f.r2.count=0;};
const boundedCalls=f=>{const sanity=Object.values(f.calls).reduce((a,b)=>a+b,0);assert.ok(sanity<=50,'Sanity calls: '+sanity);assert.ok(f.r2.count<=1000,'R2 calls: '+f.r2.count);return {sanity,r2:f.r2.count};};
const page=(i,large=false)=>({id:`test-${i}`,name:`Page ${i}`,path:i===0?'/':`/p-${i}`,title:'',description:'',showHeader:true,showFooter:true,blocks:large?Array.from({length:4},(_,b)=>({id:`block-${i}-${b}`,name:'block',type:'flow',styles:{desktop:{}},elements:Array.from({length:b===3?50:100},(_,e)=>({id:`element-${i}-${b}-${e}`,name:'text',type:'text',text:'x'.repeat(2000),styles:{desktop:{}}}))})):[]});
function fullPage(i){const p=page(i,true);let n=0;while(Buffer.byteLength(JSON.stringify(p))<768*1024){const element={id:'fill-'+i+'-'+n++,name:'fill',type:'text',text:'',styles:{desktop:{}}};const block=p.blocks.find(b=>b.elements.length<100);block.elements.push(element);const remaining=768*1024-Buffer.byteLength(JSON.stringify(p));if(remaining<0){block.elements.pop();p.description+='x'.repeat(768*1024-Buffer.byteLength(JSON.stringify(p)));break;}element.text='x'.repeat(Math.min(2000,remaining));}assert.equal(Buffer.byteLength(JSON.stringify(p)),768*1024);return p;}
 test('100 individually staged near-limit pages commit without loading 99 other page bodies',async t=>{
 const f=fixture();await initializeCatalog(f.client,f.bucket,'owner',fallback);let session=await readCatalogSession(f.client);const receipts=[];
 for(let i=0;i<100;i++){const p=fullPage(i);assert.ok(Buffer.byteLength(JSON.stringify({action:'stagePage',revision:session.revision,page:p}))<pagedRequestLimit);resetCalls(f);receipts.push((await stageCatalogPart(f.client,'owner',session.revision,p.id,p,verify,f.bucket)).receipt);boundedCalls(f);}
 const stage=boundedCalls(f);resetCalls(f);session=await commitCatalog(f.client,'owner',{revision:session.revision,receipts,deletePageIds:session.catalog.pages.map(p=>p.id)});const commit=boundedCalls(f);assert.equal(session.catalog.pages.length,100);assert.ok(f.writes.every(size=>size<4_000_000));
 const snapshot=await backupCatalog(f.client,f.bucket,'owner',{draft:session.catalog,published:null,candidate:session.catalog},'test');
 const changed=fullPage(1);changed.name='Change';f.reads.length=0;const staged=await stageCatalogPart(f.client,'owner',session.revision,changed.id,changed,verify,f.bucket);const before=new Set(session.catalog.pages.filter(p=>p.id!=='test-0'&&p.id!==changed.id).map(p=>p.part));resetCalls(f);session=await commitCatalog(f.client,'owner',{revision:session.revision,receipts:[staged.receipt]});const save=boundedCalls(f);assert.equal(f.reads.filter(id=>before.has(id)).length,0);
 resetCalls(f);await restoreCatalog(f.client,f.bucket,'owner',{id:snapshot,revision:session.revision,version:'draft',scope:[],confirmed:true});const restore=boundedCalls(f);t.diagnostic(JSON.stringify({maximumPageBytes:768*1024,stage,commit,save,restore}));
});
test('failed staging or CAS leaves root unchanged and foreign receipts are rejected',async()=>{
 const f=fixture();await initializeCatalog(f.client,f.bucket,'owner',fallback);const initial=await readCatalogSession(f.client),p=page(1),staged=await stageCatalogPart(f.client,'owner',initial.revision,p.id,p,verify);f.setFail();await assert.rejects(()=>stageCatalogPart(f.client,'owner',initial.revision,'test-2',page(2),verify));assert.equal((await readCatalogSession(f.client)).revision,initial.revision);await assert.rejects(()=>commitCatalog(f.client,'other',{revision:initial.revision,receipts:[staged.receipt]}));f.setFail();await assert.rejects(()=>commitCatalog(f.client,'owner',{revision:initial.revision,receipts:[staged.receipt]}));assert.equal((await readCatalogSession(f.client)).revision,initial.revision);
});
test('recycle records paginate beyond 100 without body inclusion',async()=>{const f=fixture();for(let i=0;i<151;i++){const id=`designerRecycle.${String(i).padStart(8,'0')}-0000-4000-8000-000000000000`;f.docs.set(id,{_id:id,_type:'designerRecycle',owner:'owner',active:true,summary:{id:`p${i}`},deletedAt:'today'});}let cursor,total=0;do{const r=await catalogRecycle(f.client,'owner',cursor);total+=r.items.length;cursor=r.nextCursor;}while(cursor);assert.equal(total,151);assert.equal((await catalogRecycle(f.client,'other')).items.length,0);});
test('publication stages selected page and navigation in one public transaction; corrupt snapshot blocks restore',async()=>{
 const f=fixture();await initializeCatalog(f.client,f.bucket,'owner',fallback);let s=await readCatalogSession(f.client);const p=page(1),a=await stageCatalogPart(f.client,'owner',s.revision,p.id,p,verify),header=structuredClone(s.header);header.blocks[0].elements.push({id:'new-link',name:'new',type:'button',text:'New',link:{pageId:p.id},styles:{desktop:{}}});const b=await stageCatalogPart(f.client,'owner',s.revision,'header',header,verify);s=await commitCatalog(f.client,'owner',{revision:s.revision,receipts:[a.receipt,b.receipt]});
 const published=await publishCatalog(f.client,f.bucket,'owner',{revision:s.revision,publishedRevision:null,scope:[p.id,'header'],confirmed:true},fallback,verify);assert.ok(published.publishedCatalog.pages.some(x=>x.id===p.id));const history=await catalogHistory(f.bucket,'owner');const id=published.snapshotId;assert.ok(history.items.some(x=>x.id===id));const snapshot=await catalogHistory(f.bucket,'owner',undefined,id),part=snapshot.snapshot.draft.pages.find(x=>x.id===p.id).part;const object=f.objects.get(`snapshots/designer-objects/${part.slice(-64)}.json`);object.text='{}';const rev=published.revision;await assert.rejects(()=>restoreCatalog(f.client,f.bucket,'owner',{id,revision:rev,version:'draft',scope:[p.id],confirmed:true}),e=>e.status===409);assert.equal((await readCatalogSession(f.client)).revision,rev);
});
test('public CAS failure exposes no staged public parts; verified snapshot restores a selected page',async()=>{
 const f=fixture();await initializeCatalog(f.client,f.bucket,'owner',fallback);let s=await readCatalogSession(f.client);f.setFail();await assert.rejects(()=>publishCatalog(f.client,f.bucket,'owner',{revision:s.revision,publishedRevision:null,scope:['home'],confirmed:true},fallback,verify));assert.equal(f.docs.has('designer-site'),false);assert.equal([...f.docs.keys()].some(id=>id.startsWith('designer-part-')),false);
 s=await publishCatalog(f.client,f.bucket,'owner',{revision:s.revision,publishedRevision:null,scope:['home'],confirmed:true},fallback,verify);const snapshot=s.snapshotId,original=s.page.name,p=structuredClone(s.page);p.name='Changed';const staged=await stageCatalogPart(f.client,'owner',s.revision,p.id,p,verify);s=await commitCatalog(f.client,'owner',{revision:s.revision,receipts:[staged.receipt]});s=await restoreCatalog(f.client,f.bucket,'owner',{id:snapshot,revision:s.revision,version:'draft',scope:['home'],confirmed:true});assert.equal(s.page.name,original);
});



test('derived validation indices stay compact for 500 multilingual overflowing elements',async()=>{
 const p=page(1);p.name='界'.repeat(120);p.blocks=Array.from({length:5},(_,b)=>({id:'block-'+b,name:'block',type:'flow',styles:{desktop:{}},elements:Array.from({length:100},(_,i)=>({id:'overflow-'+b+'-'+i,name:'界'.repeat(113)+i,type:'text',styles:{desktop:{x:-100,y:-100},tablet:{x:-100,y:-100},mobile:{x:-100,y:-100}}}))}));const index=pageIndex(p);assert.equal(index.issues.length,500);assert.ok(Buffer.byteLength(JSON.stringify(index))<pagedRequestLimit);assert.ok(index.issues.every(i=>i.widths.length===5));
 const f=fixture();await initializeCatalog(f.client,f.bucket,'owner',fallback);let s=await readCatalogSession(f.client);const staged=await stageCatalogPart(f.client,'owner',s.revision,p.id,p,verify);s=await commitCatalog(f.client,'owner',{revision:s.revision,receipts:[staged.receipt]});const id=await backupCatalog(f.client,f.bucket,'owner',{draft:s.catalog,published:null,candidate:s.catalog},'test');await restoreCatalog(f.client,f.bucket,'owner',{id,revision:s.revision,version:'draft',scope:[p.id],confirmed:true});
});
test('10,000 redirects remain in page indices and snapshot roots are stored by hash',async()=>{
 const f=fixture(),site=createDefaultSite();site.pages=Array.from({length:100},(_,i)=>({...page(i),redirectFrom:Array.from({length:100},(_,j)=>'/old-'+i+'-'+j+'-'+('x'.repeat(180)))}));await initializeCatalog(f.client,f.bucket,'owner',async()=>site);const s=await readCatalogSession(f.client);assert.ok(Buffer.byteLength(JSON.stringify(s.catalog))<100_000);assert.equal(s.catalog.pages.some(p=>'redirectFrom'in p),false);const id=await backupCatalog(f.client,f.bucket,'owner',{draft:s.catalog,published:s.catalog,candidate:s.catalog},'test');const stored=[...f.objects].find(([key])=>key.endsWith('/'+id+'.json'))[1];assert.ok(Buffer.byteLength(stored.text)<1000);const history=await catalogHistory(f.bucket,'owner',undefined,id);assert.equal(history.snapshot.candidate.pages.length,100);assert.equal([...f.objects.keys()].filter(key=>key.startsWith('snapshots/designer-catalogs/')).length,1);
});
test('post-CAS concurrent edits cannot be acknowledged as the submitted candidate',async()=>{
 const f=fixture();await initializeCatalog(f.client,f.bucket,'owner',fallback);const s=await readCatalogSession(f.client),p=page(1),staged=await stageCatalogPart(f.client,'owner',s.revision,p.id,p,verify),mutate=f.client.mutate;f.client.mutate=async ops=>{await mutate(ops);if(ops.some(m=>m.patch?.id==='drafts.designer-site')){const root=f.docs.get('drafts.designer-site');root.manifest.pages[0].name='Concurrent writer';root._rev='concurrent';}};await assert.rejects(()=>commitCatalog(f.client,'owner',{revision:s.revision,receipts:[staged.receipt]}),e=>e.status===409);
});


test('published page deletion keeps body private in recycle and allows an empty resource selection',async()=>{
 const f=fixture();await initializeCatalog(f.client,f.bucket,'owner',fallback);let s=await readCatalogSession(f.client);const p=page(1),staged=await stageCatalogPart(f.client,'owner',s.revision,p.id,p,verify);s=await commitCatalog(f.client,'owner',{revision:s.revision,receipts:[staged.receipt]});s=await publishCatalog(f.client,f.bucket,'owner',{revision:s.revision,publishedRevision:null,scope:[p.id],confirmed:true},fallback,verify);const revision=s.publishedRevision;s=await commitCatalog(f.client,'owner',{revision:s.revision,receipts:[],deletePageIds:[p.id]});assert.equal(s.publishedRevision,revision);assert.deepEqual(await catalogResources(f.client,[p.id]),{assets:[],fonts:[]});s=await publishCatalog(f.client,f.bucket,'owner',{revision:s.revision,publishedRevision:s.publishedRevision,scope:[p.id],confirmed:true},fallback,verify);assert.equal(s.publishedCatalog.pages.some(page=>page.id===p.id),false);assert.ok((await catalogRecycle(f.client,'owner')).items.some(page=>page.id===p.id));
});

test('snapshot comparison reads verified selected content and public renders can pin one immutable root',async()=>{
 const f=fixture();await initializeCatalog(f.client,f.bucket,'owner',fallback);let s=await readCatalogSession(f.client);s=await publishCatalog(f.client,f.bucket,'owner',{revision:s.revision,publishedRevision:null,scope:['home'],confirmed:true},fallback,verify);const comparison=await snapshotCatalogSession(f.bucket,'owner',s.snapshotId,'draft','home');assert.deepEqual(comparison.session.page.blocks,JSON.parse(JSON.stringify(s.page.blocks)));assert.equal((await snapshotCatalogSession(f.bucket,'owner',s.snapshotId,'draft','missing')).session,null);
 const captured=await readCatalogRoot(f.client,true),part=captured.catalog.pages[0].part;f.docs.get('designer-site').manifest.pages[0].name='Newer publication';f.docs.get('designer-site')._rev='newer';f.reads.length=0;const pinned=await readCatalogVersion(f.client,captured,'home',captured);assert.equal(pinned.revision,captured.revision);assert.equal(pinned.catalog.pages[0].part,part);assert.equal(f.reads.includes('designer-site'),false);
 const object=f.objects.get('snapshots/designer-objects/'+comparison.session.catalog.pages[0].part.slice(-64)+'.json');object.text='{}';await assert.rejects(()=>snapshotCatalogSession(f.bucket,'owner',s.snapshotId,'draft','home'),e=>e.status===409);
});
test('recycle restore can use a new safe path when its original route is occupied',async()=>{
 const f=fixture();await initializeCatalog(f.client,f.bucket,'owner',fallback);let s=await readCatalogSession(f.client);const original=page(1);original.redirectFrom=['/old-alias'];original.blocks=[{id:'preserved-block',name:'Saved content',type:'flow',styles:{desktop:{}},elements:[{id:'preserved-text',name:'Text',type:'text',text:'Preserve this content',styles:{desktop:{}}}]}];let receipt=await stageCatalogPart(f.client,'owner',s.revision,original.id,original,verify);s=await commitCatalog(f.client,'owner',{revision:s.revision,receipts:[receipt.receipt]});s=await commitCatalog(f.client,'owner',{revision:s.revision,receipts:[],deletePageIds:[original.id]});const recycled=(await catalogRecycle(f.client,'owner')).items.find(p=>p.id===original.id).recycleId;
 const occupying={...page(2),path:original.path};receipt=await stageCatalogPart(f.client,'owner',s.revision,occupying.id,occupying,verify);s=await commitCatalog(f.client,'owner',{revision:s.revision,receipts:[receipt.receipt]});const revision=s.revision;
 await assert.rejects(()=>commitCatalog(f.client,'owner',{revision,receipts:[],restoreIds:[recycled]}),e=>e.status===409);assert.equal((await readCatalogSession(f.client)).revision,revision);assert.equal(f.docs.get(recycled).active,true);
 for(const restorePaths of [{[recycled]:'/admin/hijack'},{unselected:'/restored'}])await assert.rejects(()=>commitCatalog(f.client,'owner',{revision,receipts:[],restoreIds:[recycled],restorePaths}),e=>e.status===400);assert.equal((await readCatalogSession(f.client)).revision,revision);
 s=await commitCatalog(f.client,'owner',{revision,receipts:[],restoreIds:[recycled],restorePaths:{[recycled]:'/restored-page'}});const restored=await readCatalogSession(f.client,original.id,s.revision);assert.equal(restored.page.id,original.id);assert.equal(restored.page.path,'/restored-page');assert.deepEqual(restored.page.blocks,original.blocks);assert.deepEqual(restored.page.redirectFrom,[]);assert.equal(f.docs.get(recycled).active,false);
});




test('100-page initialize and atomic publication fit external and internal subrequest limits',async t=>{
 const f=fixture(),site=createDefaultSite();site.header.blocks=[];site.footer.blocks=[];site.pages=Array.from({length:100},(_,i)=>({...page(i),blocks:[{id:'initial-block-'+i,name:'Image',type:'flow',styles:{desktop:{}},elements:[{id:'initial-image-'+i,name:'Image',type:'image',assetId:crypto.randomUUID(),alt:'Image',styles:{desktop:{}}}]}]}));const seed=async()=>site;
 resetCalls(f);await initializeCatalog(f.client,f.bucket,'owner',seed);let s=await readCatalogSession(f.client);const initialize=boundedCalls(f);let verified=0;const verifyOnce=async(value,ids)=>{verified++;assert.equal(value.pages.length,0);assert.equal(ids.length,100);await f.client.fetch('*[_id in $ids]{_id}',{ids:[]});for(const id of ids){await f.bucket.head('image-detail-'+id);await f.bucket.head('image-thumbnail-'+id);}};
 resetCalls(f);s=await publishCatalog(f.client,f.bucket,'owner',{revision:s.revision,publishedRevision:null,scope:site.pages.map(p=>p.id),confirmed:true},seed,verifyOnce);const firstPublish=boundedCalls(f);assert.equal(verified,1);
 const receipts=[];for(let i=0;i<100;i++){const p=structuredClone(site.pages[i]);p.blocks[0].elements[0].id='updated-image-'+i;p.blocks[0].elements[0].assetId=crypto.randomUUID();p.blocks.push({id:'recycled-block-'+i,name:'Private recycle',deleted:true,type:'flow',styles:{desktop:{}},elements:[{id:'recycled-text-'+i,name:'Private',type:'text',text:'Private recycled content '+i,styles:{desktop:{}}}]});resetCalls(f);receipts.push((await stageCatalogPart(f.client,'owner',s.revision,p.id,p,verify,f.bucket)).receipt);boundedCalls(f);}
 resetCalls(f);s=await commitCatalog(f.client,'owner',{revision:s.revision,receipts});const commit=boundedCalls(f);resetCalls(f);verified=0;s=await publishCatalog(f.client,f.bucket,'owner',{revision:s.revision,publishedRevision:s.publishedRevision,scope:site.pages.map(p=>p.id),confirmed:true},seed,verifyOnce);const publish=boundedCalls(f);assert.equal(verified,1);assert.equal(s.publishedCatalog.pages.length,100);t.diagnostic(JSON.stringify({initialize,firstPublish,commit,publish}));
});


test('501 images and 40 fonts verify in bounded owner/version/scope-bound batches before atomic publication',async t=>{
 const f=fixture(),site=createDefaultSite(),assets=Array.from({length:501},()=>crypto.randomUUID()),owned=new Map(),fontRows=new Map(),objects=new Map();site.header.blocks=[];site.footer.blocks=[];site.pages=[page(0)];site.pages[0].shareAssetId=assets[500];site.pages[0].blocks=Array.from({length:5},(_,b)=>({id:'media-block-'+b,name:'Media',type:'flow',styles:{desktop:{}},elements:assets.slice(b*100,b*100+100).map((id,i)=>({id:'media-'+b+'-'+i,name:'Image',type:'image',assetId:id,alt:'Verified image',styles:{desktop:{}}}))}));
 for(const id of assets){owned.set(id,{id,owner:'owner'});const files=validateProcessingResult(id,'image',{files:['thumbnail','detail'].map(role=>({role,mimeType:'image/webp',size:1,width:1,height:1,sha256:'a'.repeat(64)}))}).files;f.docs.set('designer-media-'+id,{_id:'designer-media-'+id,assetId:id,kind:'image',variants:files});for(const file of files)objects.set(file.key,{size:1,sha256:file.sha256});}
 site.fonts=Array.from({length:40},(_,i)=>({id:crypto.randomUUID(),family:'Font '+i,sha256:'b'.repeat(64),weight:400,style:'normal'}));for(const font of site.fonts){const row={...font,owner:'owner',status:'published',size:1};fontRows.set(font.id,row);objects.set(publicFontKey(row),{size:1,sha256:row.sha256});}
 let d1=0,heads=0;const storage={
  UPLOADS:{prepare(sql){return {bind(owner,...ids){return {all:async()=>{
   d1++;const rows=sql.includes('designer_fonts')?fontRows:owned;
   return {results:ids.flatMap(id=>rows.get(id)?.owner===owner?[rows.get(id)]:[])};
  }};}};}},
  PUBLISHED:{head:async key=>{f.r2.count++;heads++;const o=objects.get(key);return o?{size:o.size,checksums:{sha256:Uint8Array.from(Buffer.from(o.sha256,'hex')).buffer}}:null;}}
 };const seed=async()=>site;
 await initializeCatalog(f.client,f.bucket,'owner',seed);let session=await readCatalogSession(f.client);const request={revision:session.revision,publishedRevision:session.publishedRevision,scope:[site.pages[0].id]},batchVerify=(value,ids)=>verifyPublishedResources(storage,f.client,'owner',value,true,ids),counts=[];
 resetCalls(f);d1=0;let progress=await verifyPublicationBatch(f.client,'owner',request,seed,batchVerify);counts.push({...boundedCalls(f),d1});assert.equal(progress.verified,100);assert.equal(progress.complete,false);assert.equal(heads,240);const first=progress.verification;
 await assert.rejects(()=>requirePublicationVerification(f.client,'owner',first,f.docs.get(first).binding),e=>e.status===409);await assert.rejects(()=>verifyPublicationBatch(f.client,'foreign',{...request,verification:first},seed,batchVerify),e=>e.status===409);await assert.rejects(()=>verifyPublicationBatch(f.client,'owner',{...request,scope:['header'],verification:first},seed,batchVerify),e=>e.status===409);
 let failedChecks=0;await assert.rejects(()=>verifyPublicationBatch(f.client,'owner',{...request,verification:first},seed,async()=>{failedChecks++;throw new Error('damaged derivative');}));assert.equal(failedChecks,1);assert.equal(f.docs.has('designer-site'),false);assert.equal(f.docs.get(first).verified,100);
 while(!progress.complete){resetCalls(f);d1=0;progress=await verifyPublicationBatch(f.client,'owner',{...request,verification:progress.verification},seed,batchVerify);counts.push({...boundedCalls(f),d1});assert.ok(f.r2.count+d1<1000);}
 assert.equal(heads,1242);assert.equal(counts.length,6);const verifiedReceipt=progress.verification,binding=f.docs.get(verifiedReceipt).binding;
 const repeated=await verifyPublicationBatch(f.client,'owner',{...request,verification:verifiedReceipt},seed,async()=>{throw new Error('complete receipt must not repeat checks');});assert.equal(repeated.verification,verifiedReceipt);
 const now=Date.now();t.mock.method(Date,'now',()=>now+10*60*1000+1);await assert.rejects(()=>requirePublicationVerification(f.client,'owner',verifiedReceipt,binding),e=>e.status===409);t.mock.restoreAll();
 const requireReceipt=(_site,_ids,current)=>requirePublicationVerification(f.client,'owner',verifiedReceipt,current);await previewCatalog(f.client,request.scope,site.pages[0].id,seed,requireReceipt);resetCalls(f);d1=0;const beforeHeads=heads;session=await publishCatalog(f.client,f.bucket,'owner',{...request,confirmed:true,verification:verifiedReceipt},seed,requireReceipt);const publication=boundedCalls(f);assert.equal(heads,beforeHeads);assert.equal(session.publishedCatalog.pages.length,1);await assert.rejects(()=>verifyPublicationBatch(f.client,'owner',{...request,verification:verifiedReceipt},seed,batchVerify),e=>e.status===409);t.diagnostic(JSON.stringify({assets:501,fonts:40,batches:counts,publication}));
});
