import { portfolioSections, journeyLanes } from '../portfolio.ts';
import { projects } from '../projects.ts';
import { type PageLayout } from '../page-layout.ts';
import { type DesignerElement, type DesignerBlock, type DesignerPage, type DesignerSite, type ElementStyle, validateSite } from './model.ts';

function text(id:string,value:string,tag:DesignerElement['tag']='p',role?:DesignerElement['role']):DesignerElement {return {id,name:value.slice(0,100)||id,type:'text',text:value,tag,role,styles:{desktop:{}}};}
function media(id:string,slot:string,alt:string,role?:DesignerElement['role']):DesignerElement{return {id,name:alt,type:'image',legacySlot:slot,alt,role,styles:{desktop:{}}};}
function button(id:string,value:string,pageId:string,anchor?:string):DesignerElement{return {...text(id,value,'span','feature-button'),type:'button',link:{pageId,...(anchor?{anchor}:{})}};}
function block(id:string,name:string,elements:DesignerElement[],type:DesignerBlock['type']='flow'):DesignerBlock{return {id,name,type,elements,styles:{desktop:{}}};}
function page(id:string,name:string,path:string,blocks:DesignerBlock[]):DesignerPage{return {id,name,path,title:name,description:'',showHeader:true,showFooter:true,blocks};}
function cad(prefix:string):DesignerBlock {
 const labels:[DesignerElement['role'],string][]=[['cad-label','DESIGN IN THREE DIMENSIONS'],['cad-badge','INTERACTION DEMO · NOT PROJECT CAD'],['cad-idle','Look around. Get closer.'],['cad-description','Load the 3D view to rotate and inspect the geometry.'],['cad-load','Load 3D model ↗'],['cad-loading','Loading 3D model…'],['cad-error','The 3D view could not load.'],['cad-error-description','Your browser may not support WebGL, or the model could not be fetched.'],['cad-retry','Try again'],['cad-noscript','JavaScript is required for the interactive model.'],['cad-left','↶ Rotate left'],['cad-right','Rotate right ↷'],['cad-zoom-in','+'],['cad-zoom-out','−'],['cad-reset','Reset view'],['cad-instructions','Mouse: drag to rotate, scroll to zoom. Touch: swipe sideways to rotate, pinch to zoom; swipe vertically to scroll the page. Keyboard: focus the model and use arrow keys, or use the controls above.'],['cad-disclaimer','Simple demonstration geometry only. Your own exported GLB model will replace this example.']];
 return block(`${prefix}-cad`,'3D model',[{...text(`${prefix}-cad-viewer`,'Explore the geometry.','h2'),type:'cad'},...labels.map(([role,value])=>text(`${prefix}-${role}`,value,'p',role))]);
}
export function createDefaultSite(layout?:PageLayout):DesignerSite {
 const home=page('home','Ryan Zhao’s Portfolio','/',[
  block('hero','Hero',[media('hero-media','home.hero','Hero · propulsion experiment','hero-photo'),text('hero-title','Ryan Zhao’s Portfolio','h1','hero-title'),text('hero-caption','Your original photograph','span','hero-caption')],'hero'),
  block('bio','Biography',[media('bio-media','home.portrait','Portrait · project exhibition','portrait-photo'),text('bio-title','RYAN ZHAO:','h2'),text('bio-lead','A full-time creator.','p','bio-lead'),text('bio-intro','“I’m willing to venture boldly into any field with a forward-looking mindset and devote myself completely to mastering it.”'),text('bio-gratitude','“Much of my knowledge comes from open-source communities, guidance from teachers, and books, and I owe them tremendous gratitude.”'),text('bio-openness','“Because of that, transparency and openness are fundamental to my work. I am committed to documenting and openly sharing my research.”'),text('bio-note','Excerpts from the original portfolio · biography to be updated','span','reference-copy')],'bio'),
  block('journey','Journey',[text('journey-title','My journey to challenge\nthe inefficiency of propulsion','h2'),text('journey-intro','Three connected paths. One evolving body of work.'),...journeyLanes.flatMap(lane=>[text(`journey-lane:${lane.slug}:title`,lane.title,'h3'),...lane.steps.flatMap(step=>[text(`journey-step:${lane.slug}:${step.year}:year`,`${step.year}${step.year==='2025'?' · to Nov. 1':''}`,'span','journey-year'),{...text(`journey-step:${lane.slug}:${step.year}:title`,step.title,'p','journey-node'),link:{pageId:`work-${lane.slug}`}},...step.details.map((detail,i)=>text(`journey-step:${lane.slug}:${step.year}:detail:${i}`,detail,'p','journey-detail'))])]),text('journey-legend-label','Color indicates year:','span'),...['2023','2024','2025'].map(year=>text(`journey-legend-${year}`,`${year}${year==='2025'?' · to Nov. 1':''}`,'span','legend-chip'))],'journey'),
  cad('home'),
  ...portfolioSections.map(s=>block(s.slug,s.title,[text(`${s.slug}-number`,`SECTION ${s.number}`,'span','section-number'),text(`${s.slug}-title`,s.title,'h2'),text(`${s.slug}-quote`,`“${s.quote}”`,'blockquote'),button(`${s.slug}-button`,s.number==='I'||s.number==='II'?'Read more':'See works',`work-${s.slug}`),media(`${s.slug}-media`,`home.${s.slug}`,s.image,'feature-photo'),...(s.slug==='electronics'?[media('electronics-secondary','home.electronics.secondary','Flight computer · circuit board','secondary-photo')]:[])],'feature')),
  block('home-note','Preview note',[text('home-note-text','Design preview · Image spaces are ready for your original photographs.'),button('home-project-index','Project index ↗','projects')])
 ]);
 const work=portfolioSections.map(s=>page(`work-${s.slug}`,s.title,`/work/${s.slug}`,[
  block(`work-${s.slug}-heading`,'Heading',[button(`work-${s.slug}-back`,'← Back to portfolio','home',s.slug),text(`work-${s.slug}-number`,`SECTION ${s.number}`,'span','section-number'),text(`work-${s.slug}-title`,s.title,'h1'),text(`work-${s.slug}-quote`,`“${s.quote}”`),media(`work-${s.slug}-media`,`work.${s.slug}.hero`,s.image),text(`work-${s.slug}-work`,'The work','h2'),text(`work-${s.slug}-pending`,'Portfolio content in preparation')]),
  ...(s.projects.length?s.projects.map((title,i)=>block(`work-${s.slug}-card-${i}`,title,[media(`work-${s.slug}-photo-${i}`,`work.${s.slug}.project.${i+1}`,title),text(`work-${s.slug}-index-${i}`,`0${i+1} / PROJECT`),text(`work-${s.slug}-name-${i}`,title,'h3'),text(`work-${s.slug}-description-${i}`,'Project photographs and documentation will be added here.')])):[block(`work-${s.slug}-activity`,'Activity',[media(`work-${s.slug}-activity-photo`,`work.${s.slug}.activity`,s.layout==='team'?'Team activity':'Outreach activity'),text(`work-${s.slug}-activity-title`,s.layout==='team'?'Working together.':'Ideas worth sharing.','h2'),text(`work-${s.slug}-activity-description`,'Photographs and stories will be added here.')])]),
  block(`work-${s.slug}-next`,'Explore',[text(`work-${s.slug}-explore`,'Explore another field'),...portfolioSections.filter(x=>x.slug!==s.slug).map(x=>button(`work-${s.slug}-to-${x.slug}`,`${x.title} ↗`,`work-${x.slug}`))])
 ]));
 const simple=(id:string,name:string,path:string,entries:[string,DesignerElement['tag'],DesignerElement['role']?][])=>page(id,name,path,[block(`${id}-content`,name,entries.map(([value,tag,role],i)=>text(`${id}-text-${i}`,value,tag,role)))]);
 const projectIndex=simple('projects','Projects','/projects', [['THE PROJECT INDEX','p','eyebrow'],['Engineering projects.','h1'],['Three draft spaces for the work. Scope, roles, dates, and results await confirmation.','p','page-intro']]);
 projectIndex.blocks[0].elements.push({...text('projects-list','Project results'),type:'project-list'},...([['filter-discipline','Discipline'],['filter-tag','Tag'],['filter-all','All'],['filter-count','draft'],['filter-results','Project results'],['filter-empty','No projects match these filters. Try another discipline or tag.']] as const).map(([role,value])=>text(`projects-${role}`,value,'span',role)));
 const projectPages=projects.map(p=>{const result=simple(`project-${p.slug}`,p.title,`/projects/${p.slug}`,[[`PROJECT ${p.number} / ${p.category}`,'p','eyebrow'],[p.title,'h1'],[p.subtitle,'p','page-intro'],['Draft · Unconfirmed','span'],...p.tags.map(t=>[t,'span'] as [string,'span']),['PROJECT RECORD','p','eyebrow'],['Status','p'],['Awaiting confirmation','p'],['Role & dates','p'],['Not yet provided','p'],['Evidence','p'],['Not yet published','p'],['Project overview','h2'],[p.summary,'p'],['Documentation in preparation','h3'],['This is a project draft. No performance figures, completed experiments, or outcomes are claimed here. Measured results, simulations, and design targets will be labeled separately when source material is added.','p'],['Engineering record','h2'],['Goals, design decisions, system architecture, tests, and lessons learned will be added as verified material becomes available.','p']]);result.blocks[0].elements.unshift(button(`project-${p.slug}-back`,'← Project index','projects'));return result;});
 const header=page('global-header','Global header','/global-header',[block('header-content','Header',[{...text('header-mars','MARS','span','wordmark'),link:{pageId:'home'}},text('header-ryan','RYAN ZHAO','span','brand-subtitle'),text('header-open','Explore +','span','menu-open'),text('header-close','Close −','span','menu-close'),text('header-skip','Skip to content','span','skip-link'),...portfolioSections.map(s=>({...text(`header-nav-${s.slug}`,s.title,'span','navigation'),link:{pageId:'home',anchor:s.slug}}))],'header')]);
 const footer=page('global-footer','Global footer','/global-footer',[block('footer-content','Footer',[{...text('footer-brand','MARS / RYAN ZHAO','span','wordmark'),link:{pageId:'home'}},text('footer-note','Portfolio · Design preview','span'),text('footer-admin','管理入口 ↗','span','admin-link')],'footer')]);
 const site:DesignerSite={schemaVersion:2,header,footer,theme:{background:'#f5f1e8',color:'#171717',accent:'#e7652b',font:'garet'},fonts:[],pages:[home,...work,projectIndex,...projectPages,
  simple('about','About','/about',[['BEHIND THE WORK','p','eyebrow'],['About Ryan.','h1'],['An engineering portfolio in preparation.','p','page-intro'],['Biography pending confirmation','h2'],['Education, experience, personal interests, and current work will be added using confirmed information. This preview does not assume an institution, job title, degree, award, or publication.','p','notice']]),
  simple('contact','Contact','/contact',[['GET IN TOUCH','p','eyebrow'],['Let’s talk engineering.','h1'],['Contact details are awaiting confirmation.','p','page-intro'],['An approved email address and external profiles will appear here. No contact form or personal details are published in this preview.','p','notice']]),
  simple('updates','Updates','/updates',[['THE ENGINEERING LOG','p','eyebrow'],['Notes from the work.','h1'],['A place for design decisions, observations, and the next question.','p','page-intro'],['No published entries yet.','h2'],['Confirmed engineering notes will appear here, linked to the projects they document.','p']]),
  page('model-preview','Model preview','/model-preview',[cad('model-preview')]),
  simple('not-found','Not found','/404',[['404 / NOT FOUND','p','eyebrow'],['This page isn’t here.','h1'],['The address may have changed, or the page has not been published.','p','page-intro']]),
  simple('error','Error','/error',[['Something didn’t load.','h1'],['Please try again.','p'],['Try again','span','error-reset']])
 ]};
 site.pages.find(p=>p.id==='not-found')!.blocks[0].elements.push(button('not-found-back','Back to home ↗','home'));
 for(const project of projects)site.pages.find(p=>p.id===`project-${project.slug}`)!.blocks[0].elements.splice(4,0,{id:`project-${project.slug}-placeholder`,name:project.title,type:'image',text:project.title,alt:`${project.title}: real project photograph pending`,role:'project-placeholder',styles:{desktop:{}}});
 projectIndex.blocks[0].elements.push(text('projects-count-singular','project','span','filter-project'),text('projects-count-plural','projects','span','filter-projects'));
 footer.blocks[0].elements.push(text('shared-project-image-label','PROJECT IMAGE / PENDING','span','project-image-label'),text('shared-project-draft','Draft','span','project-draft'));
 footer.blocks[0].elements.push(text('shared-media-empty','IMAGE TO BE ADDED','span','media-empty'),text('shared-media-crop-warning','Zoomed video crop unavailable in this browser.','span','media-crop-warning'));
 for(const section of portfolioSections){home.blocks.find(b=>b.id===section.slug)!.template=`feature-${section.layout}`;const w=work.find(p=>p.id===`work-${section.slug}`)!;for(const b of w.blocks)b.template=b.id.endsWith('-heading')?'work-heading':b.id.includes('-card-')?'work-card':b.id.endsWith('-activity')?'work-activity':'work-next';}
 if(layout)applyLegacyLayout(home,layout);
 return validateSite(site);
}

function applyLegacyLayout(home:DesignerPage,layout:PageLayout) {
 for(const [blockId,oldBlock] of Object.entries(layout.blocks)) {
  const target=home.blocks.find(b=>b.id===blockId);if(!target)continue;
  for(const viewport of ['desktop','tablet','mobile'] as const){const old=viewport==='desktop'?oldBlock:oldBlock.overrides?.[viewport];if(!old)continue;if(old.height!==undefined)target.styles[viewport]={...target.styles[viewport],height:old.height};
   for(const [oldId,value]of Object.entries(old.elements)) {
    let element=oldId.startsWith('media:')?target.elements.find(e=>e.legacySlot===oldId.slice(6)):target.elements.find(e=>e.id===`${blockId}-${oldId}`);
    if(!element&&oldId.startsWith('text-')){element=text(`${blockId}-${oldId}`,viewport==='desktop'?value.text??'':'');if(viewport!=='desktop')element.styles.desktop.hidden=true;target.elements.push(element);}
    if(!element)continue;
    const {text:content,...style}=value;if(content!==undefined){if(viewport==='desktop')element.text=content;else element.textOverrides={...element.textOverrides,[viewport]:content};}element.styles[viewport]={...element.styles[viewport],...(viewport!=='desktop'&&oldId.startsWith('text-')&&!oldBlock.elements[oldId]?{hidden:false}:{}),...style} as ElementStyle;
   }
  }
 }
}
